# Use the official PyTorch image as the base image
FROM sonoisa/deep-learning-coding:pytorch1.12.0_tensorflow2.9.1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
# RUN apt-get update && apt-get install -y \
#     python3-pip \
#     python3-setuptools

# Install required Python packages
RUN pip install flask

# Run the application
CMD ["python", "./main.py"]