# Use the official PyTorch image as the base image
FROM python:3.11-alpine3.17

# Set the working directory in the container
WORKDIR /app

# Install required Python packages
RUN pip install --upgrade pip
COPY ./requirements.txt ./requirements.txt
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app
# Run the application
CMD ["python", "./main.py"]